directories:
  rawdata: data/rawdata
  procdata: data/procdata
  results: results
  logs: logs

metadata:
  supplementary:
    url: https://static-content.springer.com/esm/art%3A10.1038%2Fnm.3954/MediaObjects/41591_2015_BFnm3954_MOESM10_ESM.xlsx
    file: 41591_2015_BFnm3954_MOESM10_ESM.xlsx
    sheets:
      rnaseq:
        name: RNAseq_fpkm
        file: RNAseq_fpkm.tsv
      cnv:
        name: copy number
        file: copy_number.tsv
      mutation:
        name: pdxe_mut_and_cn2
        file: pdxe_mut_and_cn2.tsv
      pct_raw:
        name: PCT raw data
        file: pct_raw_data.tsv
      pct_curve_metrics:
        name: PCT curve metrics
        file: pct_curve_metrics.tsv
  oncotree_tissue_code_map:
    GC: STOMACH
    CRC: BOWEL
    PDAC: PANCREAS
    BRCA: BREAST
    NSCLC: LUNG
    CM: MEL

treatmentResponse:
  control_drug: untreated
